name: Generate 3D contribution graph

on:
  schedule:
    - cron: "0 1 * * *"   # daily at 01:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # <-- REQUIRED so the bot can commit the SVGs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate SVGs
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          username: mursalfk
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & push generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update 3D contribution graph" || echo "No changes to commit"
          git push
